# Railway Configuration for Spring Boot Application
# Railway will auto-detect Java/Maven project and build accordingly

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 30000
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10