# Railway Configuration for Spring Boot Application
# Following YouTube tutorial best practices with Java 25

[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 120000
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5

[variables]
PORT = "8081"
SPRING_PROFILES_ACTIVE = "production"

[nixpacks]
# Use Java 25 for Spring Boot deployment
pkgs = ["jdk25", "maven"]