# Railway Configuration for Spring Boot Application
# Railway will auto-detect Java/Maven project and build accordingly
# No health check - direct deployment

[deploy]
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3