[build]
builder = "heroku/buildpacks:20"

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[[services]]
name = "app"

[services.variables]
PORT = "8081"
JAVA_OPTS = "-Xmx512m -Xms256m"

[services.env]
SPRING_PROFILES_ACTIVE = "production"