# Railway Configuration for Spring Boot Application
# Using Railway's default build system which automatically detects Java/Maven projects

[deploy]
healthcheckPath = "/actuator/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10